from google import genai
import re
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

#  Get API key safely
API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise ValueError("❌ GEMINI_API_KEY not found in .env file")

# Initialize client
client = genai.Client(api_key=API_KEY)


def query_rag(vectorstore, query):

    query_lower = query.lower()

    #  Extract year from query
    year_match = re.search(r"\b(20\d{2})\b", query)
    year = int(year_match.group()) if year_match else None

    #  STEP 1: Semantic retrieval
    retrieved_docs = vectorstore.similarity_search(query, k=10)

    filtered_docs = []

    #  STEP 2: Metadata filtering
    for d in retrieved_docs:
        meta = d.metadata

        # Year filter
        if year:
            if not meta.get("date") or meta["date"].year != year:
                continue

        # Type filter
        doc_type = meta.get("document_type", "")

        if "email" in query_lower and doc_type != "email":
            continue

        if "report" in query_lower and doc_type != "report":
            continue

        if "contract" in query_lower and doc_type != "contract":
            continue

        filtered_docs.append(d)

    #  STEP 3: Deduplicate
    unique_docs = {}
    for d in filtered_docs:
        doc_id = d.metadata.get("document_id")
        if doc_id and doc_id not in unique_docs:
            unique_docs[doc_id] = d

    filtered_docs = list(unique_docs.values())[:3]

    print(f"After filtering (final docs): {len(filtered_docs)}")

    #  STEP 4: Build structured context
    context_parts = []

    for d in filtered_docs:
        meta = d.metadata

        date_val = meta.get("date")
        if date_val:
            date_val = str(date_val).split(" ")[0]

        context_parts.append(f"""
Document ID: {meta.get("document_id", "N/A")}
File Name: {meta.get("file_name", "N/A")}
Date: {date_val if date_val else "N/A"}
Author: {meta.get("author", "N/A")}
Type: {meta.get("document_type", "N/A")}

Content:
{d.page_content}
""")

    context = "\n\n".join(context_parts)

    #  STEP 5: Prompt
    prompt = f"""
You are a document intelligence assistant.

Use ONLY the context below.
Summarize relevant information.

Context:
{context}

Question:
{query}

Answer:
"""

    #  STEP 6: LLM call with proper error handling
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        if not response or not getattr(response, "text", None):
            return "⚠️ No response generated by LLM."

        return response.text

    except Exception as e:
        print(f"⚠️ Gemini API Error: {str(e)}")

        #  STEP 7: Fallback mode
        summary_lines = []

        for d in filtered_docs:
            meta = d.metadata

            date_val = meta.get("date")
            if date_val:
                date_val = str(date_val).split(" ")[0]

            summary_lines.append(
                f"- {meta.get('file_name', 'N/A')} | "
                f"{meta.get('document_type', 'N/A')} | "
                f"{date_val if date_val else 'N/A'}"
            )

        summary = "\n".join(summary_lines)

        return f"""
Summary (Fallback Mode):

Relevant documents:
{summary}

(Note: LLM unavailable due to API quota or error.)
"""